### ISSUE TITLE
error C3249: illegal statement or sub-expression for 'constexpr' function

### ISSUE THREAD

**Issue by virkji** [adamyaxley/Obfuscate#14]
Hi
Can you help me fix this error "statement may not appear in a constexpr function" in following section

constexpr void cipher (char* data, size_type size, key_type key)
	{
		// Obfuscate with a simple XOR cipher based on key
		for ( i = 0; i < size; i++ )
		{
			data[i] ^= char (key >> ((i % 8) * 8));
		}
	}

**Comment by adamyaxley** [comment]
Hi virkjr,

This library requires C++14 to be enabled. For some compilers you may need to set this manually in the compiler flags.

Thanks,
Adam

**Comment by virkji** [comment]
Hi Adam,
I am using visual studio 15 which I think has C++14 by default. Am I
missing something? Sorry for asking this as I am still a novice in
programming.

Thanks

**Comment by adamyaxley** [comment]
Hi virkji,

The support of C++14 in Visual Studio 2015 is partial and does not include "N3652 Extended constexpr" which is required for this library. The minimum supported Visual Studio version for this library is 2017. Please see https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=msvc-160 for a list of C++ language feature conformance.

Thanks,
Adam

**Comment by virkji** [comment]
Many thanks. I used Visual studio 2019 and that fixed the issue. Now I am
having another problem. When i call AY_OBFUSCATE using any of the following
examples:

char* var = AY_OBFUSCATE("string");
const char* var = AY_OBFUSCATE("string");
static const char* var = AY_OBFUSCATE("string");

I get following errors at compilation:

"Error (active) E0028 expression must have a constant value "
"Error C2131 expression did not evaluate to a constant"

Thanks in advance

**Comment by adamyaxley** [comment]
Hi virkji,

Unfortunately I cannot reproduce the issue that you are seeing. The automatic tests on GitHub check for these errors and they pass ok. Also the example compilers fine online at https://godbolt.org/z/YsT1nxzqT

Are you using any extra compiler flags that might be causing this?

Thanks,
Adam

**Comment by smnrock** [comment]
faced similar compiler error in VS2017 with c++17 enabled.

error C2975: 'KEY': invalid template argument for 'ay::obfuscated_data', expected compile-time constant expression.

Looks like default key needs compile time constant and using __LINE__ is not working.  If i change __LINE__ to some other hardcoded number, then no issues.
