### ISSUE TITLE
How to generate a separate key for each usage

### ISSUE THREAD

**Issue by o2e** [adamyaxley/Obfuscate#16]
Is there an easy way to do this to generate a separate password for each string at random? Without modifying the llvm source code. I have used a similar string encryption plugin on Android who generates a different password for each string in the java code.

**Comment by adamyaxley** [comment]
Hi o2e,

Thanks for the question. You can accomplish this naively by creating a key from the line number where the obfuscator is used. See below for an example:

```
#define AY_OBFUSCATE_RANDOM_KEY(data) AY_OBFUSCATE_KEY(data, 0x1111111111111111 | ((long long)__LINE__ * 42) | ((long long)__LINE__ << 32));

int main()
{
    const char* one = AY_OBFUSCATE_RANDOM_KEY("one"); // key is 1229783788650836823ull
    const char* two = AY_OBFUSCATE_RANDOM_KEY("two"); // key is 1229783797240771441ull
}
```

I would recommend trying out different key calculations to get more diverse keys.

If anybody here knows a better way please kindly share with o2e.

Thanks,
Adam

**Comment by o2e** [comment]
> #define AY_OBFUSCATE_RANDOM_KEY(data) AY_OBFUSCATE_KEY(data, 0x1111111111111111 | ((long long)__LINE__ * 42) | ((long long)__LINE__ << 32))

This is a fantastic solution! The soul of string obfuscation is to stop hackers from quickly locating key code via strings, using the same encode password could be quickly decrypted by hackers using scripting techniques. Only a different password or even a different encryption algorithm can effectively stop these awesome and annoying guys. LOL

**Comment by adamyaxley** [comment]
Next thing to do is choose a different cipher depending on the line number :)

**Comment by adamyaxley** [comment]
Thanks for the feedback. I've made this behavior default. See #17

**Comment by MarioLiebisch** [comment]
Neat idea!

But what about code files unintentionally hiding their secrets at the same line number? Imagine some files starting with a set of common static variables set:
```cpp
#include "commonHeader.h"
static const char *this_module_secret_stuff = AY_OBFUSCATE_RANDOM_KEY("...")

// Actual code starts here
```
As such I'd even consider going a tiny step further with minimal overhead by adding the address/value of `__FILE__`. This way you'd end up with original values per file (since even with string literal optimization you should get different offsets per instance, unless the file names are identical, too).

**Comment by o2e** [comment]
> Neat idea!
> 
> But what about code files unintentionally hiding their secrets at the same line number? Imagine some files starting with a set of common static variables set:
> 
> ```c++
> #include "commonHeader.h"
> static const char *this_module_secret_stuff = AY_OBFUSCATE_RANDOM_KEY("...")
> 
> // Actual code starts here
> ```
> 
> As such I'd even consider going a tiny step further with minimal overhead by adding the address/value of `__FILE__`. This way you'd end up with original values per file (since even with string literal optimization you should get different offsets per instance, unless the file names are identical, too).

This is a good approach, but in fact we use string encode key diversity only to prevent the script from decrypting large quantities and then quickly locating our important code. Therefore a small number of identical encode keys does not have much negative impact. If the most efficient way to pursue this would be to assign a different encode algorithm to each string. (I have an immature idea that we could probably pre-define multiple encode algorithms and then randomly select them at AY_OBFUSCATE, but I'm actually new to C and don't even know enough about the features of #define (whether dynamic values can be part of him))

**Comment by o2e** [comment]
Off-topic:For the use of Android ndk, can we use Obfuscate's idea for jni's RegisterNatives method to encode his corresponding function address similar to
```c++
JNINativeMethod methods[] = {{"setOut", "(Ljava/io/PrintStream;)V", (void *)XX_ENCODE((int64_t) &xxxxxx)}};
env->RegisterNatives(env->FindClass("java/lang/System"), methods, sizeof(methods) / sizeof(JNINativeMethod));
```
Then by hook to restore the encoded function address to the correct function address when RegisterNatives is finally called, I feel that the function address is set at compile time, I mean if. This should counteract some static analysis, though the gains are not very objective.

**Comment by MarioLiebisch** [comment]
> I feel that the function address is set at compile time, I mean if.
It's not. Ideally the function address changes every time the program is executed, based on where in memory it's loaded (Random Address Space Layout Randomization; ASLR), which is a security feature, making it harder to specifically call functions in memory (e.g. by code injected through buffer overruns).

**Comment by o2e** [comment]
> > I feel that the function address is set at compile time, I mean if.
> 
> It's not. Ideally the function address changes every time the program is executed, based on where in memory it's loaded (Random Address Space Layout Randomization; ASLR), which is a security feature, making it harder to specifically call functions in memory (e.g. by code injected through buffer overruns).

This feature is great, and when we remove the .symbol from our programs, it may become more difficult for hackers to do their job.
