### ISSUE TITLE
Is this thread safe?

### ISSUE THREAD

**Issue by acntwww** [adamyaxley/Obfuscate#18]
I am new to C++.  
Is the following code thread safe? 
https://github.com/adamyaxley/Obfuscate/blob/master/obfuscate.h#L139
```c++
		// Manually decrypt the string
		void decrypt()
		{
			if (m_encrypted)
			{
				cipher(m_data, N, KEY);
				m_encrypted = false;
			}
		}
```

Following code is  called from multi-threads
```c++
		operator char*()
		{
			decrypt();
			return m_data;
		}
```

**Comment by acntwww** [comment]
Hi adamyaxley,  

Thanks for your reply.

The old code is:
```C++
/// Called from multi-threads
std::string local_salt(){
    return std::string(AY_OBFUSCATE("ABCDEFG")); 
}
```

Changing it to the following:
```C++
/// Called from multi-threads
/// IS THIS version code thread-safe?
std::string local_salt(){
    static const char* p = AY_OBFUSCATE("ABCDEFG");
    return std::string(p); 
}
```

Is it thread-safe now?  OR is there any esay way to make it?

**Comment by adamyaxley** [comment]
Thanks for the question acntwww, I've added a note about thread safety to the README.
