### ISSUE TITLE
Empty data .

### ISSUE THREAD

**Issue by vega0** [adamyaxley/Obfuscate#19]
Empty data by some reason calling in atexit function.

**Comment by vega0** [comment]
Proof

![image](https://user-images.githubusercontent.com/6493857/140178052-b610f5a1-8d6b-41c2-92e5-3f3a26294bb4.png)
![image](https://user-images.githubusercontent.com/6493857/140178101-2f8c0b39-7ca0-4907-ab5b-a6f74368f4df.png)

```
#ifdef __Windows__
void __CRRNTLY_DTOR()
{
    auto result = SelfContainStorage::Instance.__windows_update_key_values_call_on_program_exit();
#ifdef Machinarium_Debug
    std::cout << "KeyValues Flushd? " << result << std::endl;
#endif
} gctor(void, __CRRNTLY_RNNNING_OBJECTS) { atexit(__CRRNTLY_DTOR); SelfContainStorage::Instance.loadInternalDataStorageBlock(); }
#elif defined(__Linux)
// NOTHING TODO, SELF MODIFIERS ... WORKING REALTIME .
#endif

```
![image](https://user-images.githubusercontent.com/6493857/140178330-73701f5b-267f-4c77-80da-a0e89e193b6e.png)
![image](https://user-images.githubusercontent.com/6493857/140178378-2d3d8c42-316c-4364-800a-8675d5128d60.png)

**Comment by adamyaxley** [comment]
Hi vega0,

Thank you for getting in touch. Apologies but I don't quite understand the issue here.

What do you mean exactly by empty data? I've tried the following but it appears to work fine:
```
// Test empty data
TEST(Obfuscate, EmptyData)
{
	auto test = AY_OBFUSCATE("");
	ASSERT_TRUE(strcmp(test, "") == 0);
	puts(test);
}
```

It looks like in your example that START_CUSTOM_DATA_KEYSIGNAT is actually not empty, but is a UTF8 string. If you have a callstack for when the atexit is called, it would be helpful.

Thanks,
Adam

**Comment by vega0** [comment]
> Hi vega0,
> 
> Thank you for getting in touch. Apologies but I don't quite understand the issue here.
> 
> What do you mean exactly by empty data? I've tried the following but it appears to work fine:
> 
> ```
> // Test empty data
> TEST(Obfuscate, EmptyData)
> {
> 	auto test = AY_OBFUSCATE("");
> 	ASSERT_TRUE(strcmp(test, "") == 0);
> 	puts(test);
> }
> ```
> 
> It looks like in your example that START_CUSTOM_DATA_KEYSIGNAT is actually not empty, but is a UTF8 string. If you have a callstack for when the atexit is called, it would be helpful.
> 
> Thanks, Adam

The descriptor based on non empty string returns empty string . When dll starts, all works fine but when the dll shutting down (with main application), returns empty string.

**Comment by vega0** [comment]
> Hi vega0,
> 
> Thank you for getting in touch. Apologies but I don't quite understand the issue here.
> 
> What do you mean exactly by empty data? I've tried the following but it appears to work fine:
> 
> ```
> // Test empty data
> TEST(Obfuscate, EmptyData)
> {
> 	auto test = AY_OBFUSCATE("");
> 	ASSERT_TRUE(strcmp(test, "") == 0);
> 	puts(test);
> }
> ```
> 
> It looks like in your example that START_CUSTOM_DATA_KEYSIGNAT is actually not empty, but is a UTF8 string. If you have a callstack for when the atexit is called, it would be helpful.
> 
> Thanks, Adam

Any ideas ?

**Comment by vega0** [comment]
> Hi vega0,
> 
> Thank you for getting in touch. Apologies but I don't quite understand the issue here.
> 
> What do you mean exactly by empty data? I've tried the following but it appears to work fine:
> 
> ```
> // Test empty data
> TEST(Obfuscate, EmptyData)
> {
> 	auto test = AY_OBFUSCATE("");
> 	ASSERT_TRUE(strcmp(test, "") == 0);
> 	puts(test);
> }
> ```
> 
> It looks like in your example that START_CUSTOM_DATA_KEYSIGNAT is actually not empty, but is a UTF8 string. If you have a callstack for when the atexit is called, it would be helpful.
> 
> Thanks, Adam

fuck, thanges to startdart string and it works 
![image](https://user-images.githubusercontent.com/6493857/140604553-023d0f49-5c42-4dca-a76f-644650586ad2.png)

**Comment by vega0** [comment]
By some reason there macros returns empty string .
![image](https://user-images.githubusercontent.com/6493857/140604833-66c8b499-d6d7-4897-b9eb-02ddb5b9c7d7.png)
But, at the program starts it work
![image](https://user-images.githubusercontent.com/6493857/140604848-1e694359-8984-4340-a8cc-239af40841bf.png)

**Comment by adamyaxley** [comment]
vega0 I wasn't able to reproduce this. I hope you managed to overcome this issue. Please get in contact if you can reproduce this in a unit test and I will have a look into it.
