### ISSUE TITLE
C version possible?

### ISSUE THREAD

**Issue by neuhaus** [adamyaxley/Obfuscate#20]
Not an issue, more of a question.

I'm looking for a solution like this but for C instead of C++. 
Is it even possible?

**Comment by MarioLiebisch** [comment]
Do you want to use it in C code or are you asking about a 100% pure C project?

**Comment by neuhaus** [comment]
Personally i just want something that works with a C program ideally with both gcc (with g++ installed) and clang.

**Comment by adamyaxley** [comment]
Hi neuhaus. C doesn't support constexpr, which is what this library uses to obfuscate the string at compile time. If you wanted to do this in C you would need to obfuscate the strings using a separate tool before compiling the program.
