### ISSUE TITLE
Error C2131 - expression did not evaluate to a constant

### ISSUE THREAD

**Issue by quadrustech** [adamyaxley/Obfuscate#23]
Hello,

The latest code doesn't work with VS 2022 (in debug mode)

Error C2131 - expression did not evaluate to a constant

when ay::generate_key is used

Thanks

**Comment by William-Brumble** [comment]
Change this on line 34:
```cpp
#define AY_OBFUSCATE_DEFAULT_KEY ay::generate_key(__line__)
```
To a value, I chose to input 34, which is what __line__ is supposed to do.
```cpp
#define AY_OBFUSCATE_DEFAULT_KEY ay::generate_key(34)
```
