### ISSUE TITLE
[question] String casting question

### ISSUE THREAD

**Issue by Kaspek2480** [adamyaxley/Obfuscate#25]
I was quite annoyed while i must use `string(AY_OBFUSCATE("test"))` each time i want to obfuscate string, i did small rewrite of library, but i'm not sure if that usage is safe. My code: 

```
#define OBFUSCATE(data) \
    []() -> string {         \
        const ay::key_type key = AY_OBFUSCATE_DEFAULT_KEY; \
        static_assert(sizeof(decltype(key)) == sizeof(ay::key_type), "key must be a 64 bit unsigned integer"); \
        static_assert((key) >= (1ull << 56), "key must span all 8 bytes"); \
        constexpr auto n = sizeof(data)/sizeof(data[0]); \
        constexpr auto obfuscator = ay::make_obfuscator<n, key>(data); \
        static auto obfuscated_data = ay::obfuscated_data<n, key>(obfuscator); \
        return obfuscated_data.operator char *(); \
    }()
```

**Comment by MarioLiebisch** [comment]
What's stopping you from simply doing something like this, keeping compatibility etc. **and** ensuring identical behavior at the same time?

```cpp
auto operator "" _enc(const char *text, size_t) -> std::string {
  return AY_OBFUSCATE(text);
}

const auto my_secret = "It's a secret to everybody!"_enc;
```
(One could achieve the same using a macro, obviously.)

**Comment by MarioLiebisch** [comment]
And one minor note regarding your snippet. IMO you should **never ever** call a conversion operator manually (hinting at code smell). The compiler should pick the correct one on its own (it knows you want to return a string after all), but if you still insist on the explicit way, use a cast instead:

```cpp
return static_cast<char*>(obfuscated_data);
```

**Comment by Kaspek2480** [comment]
> What's stopping you from simply doing something like this, keeping compatibility etc. **and** ensuring identical behavior at the same time?
> 
> ```c++
> auto operator "" _enc(const char *text, size_t) -> std::string {
>   return AY_OBFUSCATE(text);
> }
> 
> const auto my_secret = "It's a secret to everybody!"_enc;
> ```
> 
> (One could achieve the same using a macro, obviously.)

I'll check that solution, but seems to be a very good idea, thanks
