### ISSUE TITLE
Update README regarding multi-threading support

### ISSUE THREAD

**Issue by adamyaxley** [adamyaxley/Obfuscate#28]
Now that we use a thread_local in the anonymous lambda we have better multi-threading support out of the box and should update the README with specifics.

**Comment by cpsauer** [comment]
@inie0722, what is the status here? Confirming that it is safe to use the library from multiple threads (contrary to the readme) and perhaps now safe to also use individual strings from multiple threads?

**Comment by inie0722** [comment]
thread_local just guarantees that each thread has its own copy of the string.
String instances themselves are still not thread-safe.

**Comment by inie0722** [comment]
https://en.cppreference.com/w/cpp/language/storage_duration

**Comment by cpsauer** [comment]
Thanks for a quick reply! That much I got, though :)

I was more asking for guidance on the thread safety of the interface, along the lines of the original issue.

To confirm: It is now okay to use `AY_OBFUSCATE` in a function that is called from multiple threads concurrently, right?
(Though not to capture the underlying instances, pass between threads, and mutate them concurrently.)
(This would be *very* different from the readme, which would indicate that even two different uses of the AY_OBFUSCATE macro cannot be safely used concurrently.)

**Comment by inie0722** [comment]
Yes, it is safe to call AY_OBFUSCATE from multiple threads.
But don't pass the underlying instance returned by AY_OBFUSCATE to other threads.
The underlying instance is not thread safe.

```cpp
//This piece of code is thread safe
void Fun()
{
    for (size_t i = 0; i < 1000; i++)
    {
        auto &obj = AY_OBFUSCATE("Hello World");
        obj.decrypt();
        std::cout << obj << std::endl;
        obj.encrypt();
    }
}

int main()
{
    std::thread th_1(Fun);
    std::thread th_2(Fun);

    th_1.join();
    th_2.join();
    return 0;
}
```

```cpp
//This code is not thread safe
void Fun()
{
    for (size_t i = 0; i < 1000; i++)
    {
        auto &obj = AY_OBFUSCATE("Hello World");
        obj.decrypt();
        
        std::thread th([&](){
            std::cout << obj << std::endl;
        });
        
        obj.encrypt();

        th.join();
    }
}

int main()
{
    Fun();
    return 0;
}
```

**Comment by adamyaxley** [comment]
Thanks for the discussion and examples! I've incorporated this into the README.

**Comment by cpsauer** [comment]
Thanks you so much, both of you :)
