### ISSUE TITLE
[Question] Free the allocated memory

### ISSUE THREAD

**Issue by TheVinhLuong** [adamyaxley/Obfuscate#29]
Sorry if this is a dumb question since I am not so familiar with C++.

Let's say I declared a variable like this:
```
 char* secretKey = AY_OBFUSCATE("losdasd");
```

Do I need to free the memory allocated for `secretKey` after using it? Thanks for reading.

**Comment by MarioLiebisch** [comment]
No. `AY_OBFUSCATE()` creates a static object at compile time. When accessed, it decrypts its data to memory that's permanently allocated to said object and returns a pointer to that. It's automatically freed once your program ends.

In other words: Just treat it as a constant string literal and you should be fine.

**Comment by TheVinhLuong** [comment]
@MarioLiebisch Thank you for the answer. Closing the issue.
