### ISSUE TITLE
Obfuscate obfuscator

### ISSUE THREAD

**Issue by assembler65** [adamyaxley/Obfuscate#30]
Thanks for this really pretty piece of code. It is amazing and it works fine.

However for me there's a tiny problem with class and variable naming.
One class is called obfuscator and a variable is obfuscated_data. This shows up in the binary in case it is released with debug info (yes, not really a good idea), but google tells any hacker what's behind the scenes in this case.

Renaming to a less story-telling name would be nice. Hm, users of your header can do this on their own, but a hint might be good.

Fx

**Comment by adamyaxley** [comment]
Hi assembler65, you're right that renaming the class could make it harder for a hacker to know where to look but distributing a security sensitive piece of software with debug symbols is going to cause plenty of other issues too I imagine.

For that reason, I'll close this issue as "won't fix" for now, but if you feel like it would be beneficial if it was highlighted in the readme then feel free to make that addition yourself and create a pull request and I'll be happy to take a look.
