### ISSUE TITLE
add support for wchar_t string leterals

### ISSUE THREAD

**Issue by z16166** [adamyaxley/Obfuscate#40]
for example, const std::wstring s = (const wchar_t *)AY_OBFUSCATE(L"test");

wchar_t is implementation-dependent, it's 2-bytes in Windows, while may be 4-bytes in Linux x86_64.

**Comment by adamyaxley** [comment]
Thanks for reporting this. It's similar to another piece of work for unicode literals that I think we can build off to add support for wchar_t.

I'll have a look into it soon.

**Comment by adamyaxley** [comment]
This should now be possible with #39
Please create another issue if you encounter any limitations.
