### ISSUE TITLE
C++20 support

### ISSUE THREAD

**Issue by geijnmh** [adamyaxley/Obfuscate#44]
Hi Adam / maintainers

Came across your library in search for a mild obfuscation solution in my project.
I compule against C++20 standard and I though it could be useful to make the obfuscate.h file use the C++20 features consteval and the STL std::remove_cvref<T> in case the header is compiled with C++20 standard enabled.

Are you interested if I share a solution to use these features on a separate branch?

Regards
Maarten

**Comment by adamyaxley** [comment]
Hi Maarten,

Yes if you think it would improve the library please go ahead and open a pull request when its ready to merge.

To get onto the official branch you'd have to make sure it still compiles with C++14.

Thanks,
Adam

**Comment by geijnmh** [comment]
Hi Adam,

Thanks. I tried to push a new branch, but I get a permission denied error. Cannot seem to find an option in Github either. Is there any possibility you can give me push permissions for feature branches?

Thanks

**Comment by MarioLiebisch** [comment]
You'll have to create your own fork (see top right on the project's Github page), then create a new branch (as you did) and push that branch to your own fork. You can then create a pull request on the official repo.

There's no need to checkout your fork. Instead you can add your own fork as an extra remote to your local repository (needed only once):

```bat
git remote add mine checkout-url-for-your-own-fork
```

Then change the upstream for your local branch to said remote (do this once per branch):

```bat
git branch --set-upstream-to mine/your-branch-name
```

You should now be able to push, the changes/branches will land in your own fork.

Once done, you can open GitHub and it should offer you to create a pull request.

**Comment by geijnmh** [comment]
HI Mario,

Thanks. I will try that.

/Maarten
