### ISSUE TITLE
Cant obfuscate arrays!!!!!!

### ISSUE THREAD

**Issue by helloworld0000red** [adamyaxley/Obfuscate#46]
std::string urlArray[] = { AY_OBFUSCATE("google.com") };

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	E0312	no suitable user-defined conversion from "ay::obfuscated_data<29Ui64, 520515158038145003Ui64, ay::char_type<const char &>>" (aka "ay::obfuscated_data<29Ui64, 520515158038145003Ui64, char>") to "std::string" exists	C:\Users\\source\repos\\\.cpp	69

**Comment by MarioLiebisch** [comment]
As a workaround, you should be able to use one of two possible solutions here:

* Create use `const char* urlArray[]` instead.
* Create a custom macro ```#define AY_OBFUSCATE_CC(x) static_cast<const char *>(AY_OBFUSCATE(x))``` and use that instead.

**Comment by helloworld0000red** [comment]
thx
