### ISSUE TITLE
Clang fails to find a suitable conversion to `std::string`

### ISSUE THREAD

**Issue by MarioLiebisch** [adamyaxley/Obfuscate#5]
The following two lines in `obfuscate_test_bloat.cpp`

    const std::string username = AY_OBFUSCATE("root");
    const std::string password = AY_OBFUSCATE("password");

trigger an error when building with Clang under MSVC:

    error : no viable conversion from 'ay::obfuscated_data<sizeof ("root") / sizeof ("root"[0]), '.'>' to 'const std::string' (aka 'const basic_string<char, char_traits<char>, allocator<char> >')

I'm not really sure why it won't pick the `operator char*()` for conversion.

Explicitly adding a conversion operator fixes the issue (although I'm aware this isn't really ideal):

    operator std::string()
    {
        decrypt();
        return m_data;
    }

Host: Windows 10 x64
MSVC Tools: 14.23.28105 (Visual Studio 2019 16.3.10)
Clang: 8.0.1 (installed through VS Installer)

To reproduce:
* Use the python script to create the solution and project files.
* Open the solution in MSVC.
* Select all projects and switch their platform toolset to LLVM.
* Try to compile `obfuscate_test_bloat_on`.

Haven't had a chance to test it under other systems though.

**Comment by zJanny** [comment]
Just declare your string as auto

**Comment by adamyaxley** [comment]
Hi @MarioLiebisch 

Apologies for the late follow up on this one, and your detailed repro instructions.

I too am unsure why clang doesn't choose the implicit char* operator. One workaround is to use the `std::string` constructor directly like:

```
const std::string username(AY_OBFUSCATE("root"));
const std::string password(AY_OBFUSCATE("password"));
```

I've updated the the code and README to use this way instead as it seems to work on both MSVC and Clang.

Thanks,
Adam
