### ISSUE TITLE
Solving the "C3493" error

### ISSUE THREAD

**Issue by Arqenza** [adamyaxley/Obfuscate#7]
I apologize for the rudimentary question, but please help me.
In this code, I am getting error "C3493". (https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c3493?view=msvc-160)
```	
const char KEY = '@';
auto abc = AY_OBFUSCATE_KEY("My string",KEY);
```
How can I solve this?
Thank you in advance.

**Comment by adamyaxley** [comment]
Hi @Arqenza

Thanks for the question. Try this:

```
static constexpr char KEY = '@';
```

`KEY` is used as a template parameter in a lambda expression so it needs to be constexpr and static. You could also do:

```
#define KEY '@'
auto abc = AY_OBFUSCATE_KEY("My string",KEY);
```

Or

```
auto abc = AY_OBFUSCATE_KEY("My string",'@');
```

Hope that helps!

Thanks,
Adam

**Comment by Arqenza** [comment]
I didn't expect such a quick answer to my rudimentary question.
I can now move forward.
I am sorry that I can't share my joy in person.
I really appreciate it.
I hope one day I can publish my work and tell you about it.
I'm looking forward to that day.
